StudentEnrollmentApp/Models/ErrorViewModel.cs
namespace StudentEnrollmentApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StudentEnrollmentApp/Controllers/CourseController.cs
using BLL;
using Entities.Entities;
using Microsoft.AspNetCore.Mvc;

namespace StudentEnrollmentApp.Controllers
{
    public class CourseController : Controller
    {
        CourseService courseService = new CourseService();
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RegisterCourse([FromBody] Course courseFormData)
        {
            var response = courseService.AddCourseService(courseFormData);
            return Json(response);
        }

    }
}

StudentEnrollmentApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StudentEnrollmentApp.Models;
using System.Diagnostics;

namespace StudentEnrollmentApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StudentEnrollmentApp/Controllers/StudentController.cs
using BLL;
using Entities.Entities;
using Microsoft.AspNetCore.Mvc;

namespace StudentEnrollmentApp.Controllers
{
    public class StudentController : Controller
    {

        StudentService studentService = new StudentService();
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// post method to register new student
        /// </summary>
        /// <param name="studentFormData"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult RegisterStudent([FromBody] Student studentFormData)
        {
            var response = studentService.AddStudentService(studentFormData);
            return Json(response);
        }
    }
}

StudentEnrollmentApp/Controllers/StudentEnrollmentController.cs
using BLL;
using Microsoft.AspNetCore.Mvc;

namespace StudentEnrollmentApp.Controllers
{
    public class StudentEnrollmentController : Controller
    {
        StudentEnrollmentService studentEnrollmentService = new StudentEnrollmentService();

        public IActionResult Index()
        {

            var response = studentEnrollmentService.GetStudentCourseForEnrollment();
            return View(response);
        }

        [HttpPost]
        public IActionResult UpdateStudentEnrollments([FromBody] Dictionary<int, List<int>> studentEnrollments)
        {
            var response = studentEnrollmentService.UpdateEnrollment(studentEnrollments);
            return View(response);
        }

    }
}

StudentEnrollmentApp/Views/Course/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

<center><h3>Register New Student</h3></center>

<script type="text/javascript">

    $(document).ready(function () {
        $('#alertSuccess').hide();
        $('#alertDanger').hide();
        $('#spinner').hide();

    })


    function Register() {

        $('#spinner').show();

        var courseObj = {
            CourseName: $('#coursename').val(),
            StartDate: $('#startdate').val(),
            EndDate: $('#enddate').val()
        };

        $.ajax({

            url: '/Course/RegisterCourse',
            type: 'POST',
            contentType: 'application/json',
            data: JSON.stringify(courseObj),
            success: function (response) {
                if (response == 'success') {
                    $('#spinner').hide();
                    $('#alertSuccess').show();
                    $('#alertSuccess').text('New Course has been successfully registered');
                }
                else {
                    $('#spinner').hide();
                    $('#alertDanger').show();
                    $('#alertDanger').text('some error occured, try again!');
                }
            },
            error: function (errormessage) {
                $('#spinner').hide();
                $('#alertDanger').show();
                $('#alertDanger').text(errormessage.responseText);
            }

        });


    }


</script>


<div class="container">

    <form>

        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="form-group">
                    <input type="text" class="form-control" id="coursename" placeholder="Course Name" />
                </div>
            </div>
        </div>

        <br />

        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="form-group">
                    <input type="date" class="form-control" id="startdate" placeholder="Start Date" />
                </div>
            </div>
        </div>

        <br />

        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="form-group">
                    <input type="date" class="form-control" id="enddate" placeholder="End Date" />
                </div>
            </div>
        </div>
        <br />

        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="form-group">
                    <button type="button" class="btn btn-primary" id="btnAdd" onclick="Register();">Register</button>
                </div>
            </div>
        </div>

        <br />

        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="alert alert-success alert-dismissible fade show" id="alertSuccess" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="alert alert-danger" id="alertDanger"></div>

            </div>
        </div>
    </form>

    <center>
        <div class="spinner-border" role="status" id="spinner">
            
        </div>
    </center>

</div>

StudentEnrollmentApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

StudentEnrollmentApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentEnrollmentApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StudentEnrollmentApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StudentEnrollmentApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student Registration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Course Registration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StudentEnrollment" asp-action="Index">Student Enrollment</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - StudentEnrollmentApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StudentEnrollmentApp/Views/Student/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

<center><h3>Register New Student</h3></center>

<script type="text/javascript">

    $(document).ready(function(){
        $('#alertSuccess').hide();
        $('#alertDanger').hide();
        $('#spinner').hide();

    })


    function Register(){
        $('#spinner').show();
        var studentObj = {
            FirstName: $('#firstname').val(),
            LastName: $('#lastname').val(),
            Email: $('#email').val()
        };

        $.ajax({

            url: '/Student/RegisterStudent',
            type: 'POST',
            contentType: 'application/json',
            data: JSON.stringify(studentObj),
            success: function (response) {
                if (response == 'success') {
                    $('#spinner').hide();
                    $('#alertSuccess').show();
                    $('#alertSuccess').text('Student has been successfully registered');
                }
                else{
                    $('#spinner').hide();
                    $('#alertDanger').show();
                    $('#alertDanger').text('some error occured, try again!');
                }
            },
            error: function (errormessage) {
                $('#spinner').hide();
                $('#alertDanger').show();
                $('#alertDanger').text(errormessage.responseText);
            }

        });


    }


</script>


<div class="container">

    <form>

        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="form-group">
                    <input type="text" class="form-control" id="firstname" placeholder="First Name" />
                </div>
            </div>
        </div>

        <br/>

        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="form-group">
                    <input type="text" class="form-control" id="lastname" placeholder="Last Name" />
                </div>
            </div>
        </div>

        <br />

        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="form-group">
                    <input type="email" class="form-control" id="email" placeholder="Email" />
                </div>
            </div>
        </div>
        <br />

        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="form-group">
                    <button type="button" class="btn btn-primary" id="btnAdd" onclick="Register();">Register</button>
                </div>
            </div>
        </div>

        <br />

        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="alert alert-success" id="alertSuccess"></div>
                <div class="alert alert-danger" id="alertDanger"></div>

            </div>
        </div>
    </form>

    <center>
        <div class="spinner-border" role="status" id="spinner">
        </div>
    </center>

</div>

StudentEnrollmentApp/Views/StudentEnrollment/Index.cshtml
@model List<Entities.ViewModels.StudentCourseVM> 

<center><h3>Student Enrollment</h3></center>


<script type="text/javascript"> 
    
    function UpdateEnrollments() {

        var studentEnrollmentObj = {};

        $('input[name="selectedCourse"]:checked').each(function () {
            var studentId = parseInt($(this).attr('id').split('_')[1]);
            var courseId = parseInt($(this).val());

            if (!studentEnrollmentObj[studentId]) {
                studentEnrollmentObj[studentId] = [];
            }

            studentEnrollmentObj[studentId].push(courseId)

        });

        console.log(studentEnrollmentObj);

        $.ajax({
            url: '/StudentEnrollment/UpdateStudentEnrollments',
            type: 'POST',
            contentType: 'application/json',
            data: JSON.stringify(studentEnrollmentObj),
            success: function (response) {

            },
            error: function (errormessage) {

            },
        });



    }


</script>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>
                Student Name
            </td>
            <td>
                Courses
            </td>
        </tr>
    </thead>
    <tbody>
        @foreach(var student in Model)
        {
            <tr>
                <td>
                    @student.FirstName
                </td>
                <td>
                    @foreach(var courseIndex in Enumerable.Range(0, student.Courses.Count()))
                    {

                        var checkBoxId = $"courseCheckBox_{student.StudentId}_{courseIndex}";

                        <input type="checkbox"
                               id="@checkBoxId"
                               name="selectedCourse" 
                            value="@student.CourseIds[courseIndex]" 
                            @(student.Checked[courseIndex] ? "checked" : "") />

                        <label for="@courseIndex">@student.Courses[courseIndex]</label>
                        <span>||</span>
                    }
                </td>
            </tr>
        }

    </tbody>
</table>

<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="form-group">
            <button type="button" class="btn btn-primary" id="btnSave" onclick="UpdateEnrollments();">Save</button>
        </div>
    </div>
</div>